export interface CoinRecord {
  name: string;
  slug: string;
  ticker: string;
  description: string;
  long_description: string;
  chain: string;
  launch_platform: string;
  contract_address: string;
  price_usd: number;
  market_cap: number;
  volume_24h: number;
  price_change_24h: number;
  is_featured: boolean;
  is_trending: boolean;
  is_new: boolean;
  is_indexed: boolean;
  tags: string[];
  logo_url: string;
  banner_url: string;
  data_source: string;
  external_data_id: string;
  launch_date: string;
}

export const coinSeedData: CoinRecord[] = [
  {
    name: 'JFK Memecoin',
    slug: 'jfk',
    ticker: 'JFK',
    description: '$JFK is a PolitiFi memecoin on Solana launched on pump.fun on May 18, 2024. It bonded in under 5 minutes and reached an ATH of $2.2M market cap, making it one of the most resilient political memecoins on Solana.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'EzRasdye3wnQ5ZGzLFhvp2L1TT42k3Qa3jFsoUibWh39',
    price_usd: 0.0000022,
    market_cap: 2200,
    volume_24h: 150000,
    price_change_24h: 0,
    is_featured: true,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'pump.fun', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-05-18',
  },
  {
    name: 'TRUMP',
    slug: 'trump',
    ticker: 'TRUMP',
    description: '$TRUMP is the official meme coin of Donald Trump, launched in January 2025 shortly before his presidential inauguration. It quickly became one of the highest-market-cap political tokens in crypto history.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: '6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN',
    price_usd: 12.5,
    market_cap: 2500000000,
    volume_24h: 300000000,
    price_change_24h: -3.2,
    is_featured: false,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'maga', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2025-01-17',
  },
  {
    name: 'MAGA',
    slug: 'maga',
    ticker: 'MAGA',
    description: '$MAGA is a grassroots political memecoin on Solana celebrating the Make America Great Again movement. It has built a strong community of political crypto enthusiasts since its launch.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'MaGAi6rBCRuTyxN2Vmf8xi3ExMYFmMkLyD3jBiXiby',
    price_usd: 0.0035,
    market_cap: 35000000,
    volume_24h: 4000000,
    price_change_24h: 2.1,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'maga', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-03-01',
  },
  {
    name: 'BODEN',
    slug: 'boden',
    ticker: 'BODEN',
    description: '$BODEN is a satirical political memecoin on Solana themed around Joe Biden. It gained significant traction during the 2024 election cycle as part of the PolitiFi wave.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'CKfatsPMUf8SkiURsDXs7eK6GWb4Jsd6UDbs7twMCWxo',
    price_usd: 0.0008,
    market_cap: 8000000,
    volume_24h: 900000,
    price_change_24h: -1.5,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'pump.fun', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-04-10',
  },
  {
    name: 'TREMP',
    slug: 'tremp',
    ticker: 'TREMP',
    description: '$TREMP is a parody political memecoin on Solana inspired by Donald Trump. It was one of the early PolitiFi tokens that paved the way for the political memecoin category.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'FU1q8vJpZNUrmqsciSjp8bAKKidGsLmouB8CBdf8TKQv',
    price_usd: 0.00045,
    market_cap: 4500000,
    volume_24h: 500000,
    price_change_24h: 0.8,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'pump.fun', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-02-15',
  },
  {
    name: 'KAMALA',
    slug: 'kamala',
    ticker: 'KAMALA',
    description: '$KAMALA is a political memecoin on Solana centered around Kamala Harris. It surged during the 2024 presidential campaign as PolitiFi tokens dominated crypto social discourse.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC',
    price_usd: 0.00012,
    market_cap: 1200000,
    volume_24h: 200000,
    price_change_24h: -2.3,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'pump.fun', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-07-22',
  },
  {
    name: 'GIGA',
    slug: 'giga',
    ticker: 'GIGA',
    description: '$GIGA is a sigma/gigachad themed memecoin on Solana that became a cultural touchstone in the PolitiFi and internet culture memecoin space. Its community rallied around the giga chad meme.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'GigAiMb1RnmrxRxFJoRJPyTnFQjJ2iFqU2y7tivQHoNs',
    price_usd: 0.00078,
    market_cap: 7800000,
    volume_24h: 950000,
    price_change_24h: 4.2,
    is_featured: false,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'pump.fun', 'meme', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-05-01',
  },
  {
    name: 'SIGMA',
    slug: 'sigma',
    ticker: 'SIGMA',
    description: '$SIGMA rides the sigma male internet meme wave as a Solana memecoin. Part of the broader PolitiFi and internet culture movement on pump.fun, it appeals to the irony-aware crypto crowd.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'SiGmAMBiSmH9X5HQKhFYmRjvSZe7FzQAuP3Kv4iFixy',
    price_usd: 0.000034,
    market_cap: 340000,
    volume_24h: 45000,
    price_change_24h: 1.1,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'pump.fun', 'meme'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-06-10',
  },
  {
    name: 'BASED',
    slug: 'based',
    ticker: 'BASED',
    description: '$BASED is a community-driven memecoin on Solana celebrating the "based" internet culture ethos. It has cultivated a loyal following among contrarian and politically-minded crypto users.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'BASEDhJpjzLSKKR9NJZsGnEXRR3z9iuT9z9VvGJQjj4K',
    price_usd: 0.000056,
    market_cap: 560000,
    volume_24h: 70000,
    price_change_24h: 0.3,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'pump.fun', 'meme', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-04-20',
  },
  {
    name: 'DOLAND',
    slug: 'doland',
    ticker: 'DOLAND',
    description: '$DOLAND is a humorous political memecoin on Solana, a play on Donald Trump\'s name that gained traction in PolitiFi circles. It represents the lighter side of political crypto culture.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'DoLaNdTrUmPmEmEcOiNsOLaNa1111111111111111111',
    price_usd: 0.000018,
    market_cap: 180000,
    volume_24h: 22000,
    price_change_24h: -0.5,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['politifi', 'pump.fun', 'meme'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-03-15',
  },
  {
    name: 'BONK',
    slug: 'bonk',
    ticker: 'BONK',
    description: '$BONK is the original Solana dog coin that airdropped to the community in December 2022. It sparked the Solana memecoin renaissance and remains one of the largest memecoins by market cap on the network.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263',
    price_usd: 0.000022,
    market_cap: 1500000000,
    volume_24h: 80000000,
    price_change_24h: 1.8,
    is_featured: false,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['dog', 'community', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2022-12-25',
  },
  {
    name: 'dogwifhat',
    slug: 'wif',
    ticker: 'WIF',
    description: '$WIF (dogwifhat) is a Solana memecoin featuring a dog wearing a pink hat that became a cultural phenomenon. It reached billions in market cap and became the flagship Solana dog memecoin.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm',
    price_usd: 1.85,
    market_cap: 1850000000,
    volume_24h: 120000000,
    price_change_24h: -2.1,
    is_featured: false,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['dog', 'community', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2023-11-20',
  },
  {
    name: 'Popcat',
    slug: 'popcat',
    ticker: 'POPCAT',
    description: '$POPCAT is a Solana memecoin based on the viral Popcat internet meme. It surged to over $1B market cap in 2024, demonstrating the power of internet culture in driving memecoin value.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: '7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr',
    price_usd: 0.85,
    market_cap: 850000000,
    volume_24h: 65000000,
    price_change_24h: 3.4,
    is_featured: false,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['meme', 'community', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-01-10',
  },
  {
    name: 'cat in a dogs world',
    slug: 'mew',
    ticker: 'MEW',
    description: '$MEW (cat in a dogs world) is a Solana memecoin representing a cat that dares to exist in a dog-dominated memecoin landscape. It gained a massive following for its contrarian premise.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREkzUofMkWm',
    price_usd: 0.0095,
    market_cap: 380000000,
    volume_24h: 25000000,
    price_change_24h: 0.7,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['cat', 'community', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-03-28',
  },
  {
    name: 'Book of Meme',
    slug: 'bome',
    ticker: 'BOME',
    description: '$BOME (Book of Meme) was one of the fastest tokens to reach $1B market cap, launched on pump.fun and achieving its milestone in under 24 hours. It represents the peak of pump.fun launch mania.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82',
    price_usd: 0.0068,
    market_cap: 285000000,
    volume_24h: 18000000,
    price_change_24h: -1.2,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-03-14',
  },
  {
    name: 'Myro',
    slug: 'myro',
    ticker: 'MYRO',
    description: '$MYRO is a Solana dog memecoin named after Raj Gokal\'s (Solana co-founder) dog. It became one of the top dog coins on Solana with strong community support from within the Solana ecosystem.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'HhJpBhRRn4g56VsyLuT8DL5Bv31HkXqsrahTTUCZeZg4',
    price_usd: 0.0082,
    market_cap: 82000000,
    volume_24h: 5500000,
    price_change_24h: 2.8,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['dog', 'community', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2023-12-01',
  },
  {
    name: 'Peanut the Squirrel',
    slug: 'pnut',
    ticker: 'PNUT',
    description: '$PNUT is a Solana memecoin inspired by Peanut, a squirrel whose story went viral. It surged after the story gained national media attention, reaching hundreds of millions in market cap.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: '2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump',
    price_usd: 0.62,
    market_cap: 620000000,
    volume_24h: 45000000,
    price_change_24h: 5.3,
    is_featured: false,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'animal', 'community', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-10-28',
  },
  {
    name: 'Goatseus Maximus',
    slug: 'goat',
    ticker: 'GOAT',
    description: '$GOAT (Goatseus Maximus) became the first AI-endorsed memecoin after an autonomous AI agent on X began promoting it. It launched a new meta of AI-driven token narratives.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump',
    price_usd: 0.48,
    market_cap: 480000000,
    volume_24h: 35000000,
    price_change_24h: -3.8,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'ai', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-10-15',
  },
  {
    name: 'FWOG',
    slug: 'fwog',
    ticker: 'FWOG',
    description: '$FWOG is a Solana memecoin themed around the beloved frog/fwog internet meme. It built a passionate community and became one of the top animal memecoins on the Solana network.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'A8C3xuqscfmyLrte3VmTqrAq8kgMASius9AFNANwpump',
    price_usd: 0.0035,
    market_cap: 35000000,
    volume_24h: 2800000,
    price_change_24h: 1.4,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'animal', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-07-05',
  },
  {
    name: 'Ponke',
    slug: 'ponke',
    ticker: 'PONKE',
    description: '$PONKE is a Solana memecoin featuring a cartoon monkey character. It became one of the most recognizable memecoin mascots on Solana, with strong community art and culture.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: '5z3EqYQo9HiCEs3R84RCDMu2n7anpDMxRhdK8PSWmrRC',
    price_usd: 0.22,
    market_cap: 220000000,
    volume_24h: 15000000,
    price_change_24h: 2.2,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['animal', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2023-12-10',
  },
  {
    name: 'Retardio',
    slug: 'retardio',
    ticker: 'RETARDIO',
    description: '$RETARDIO is an irreverent Solana memecoin that embraces absurdist internet humor. Despite its controversial name, it built a loyal community and became a notable pump.fun success story.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: '6ogzHhzdrQr9Pgv6hZ2MNze7UrzBMAVyqMaU6YNkBh2',
    price_usd: 0.055,
    market_cap: 55000000,
    volume_24h: 4200000,
    price_change_24h: -0.9,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-04-01',
  },
  {
    name: 'Michi',
    slug: 'michi',
    ticker: 'MICHI',
    description: '$MICHI is a Solana cat memecoin that became one of the top cat tokens on the network. Named after the Spanish/Japanese word for cat, it built a culturally diverse community.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: '5mbK36SZ7J19An8jFochhQS4of8g6BwUjbeCSxBSoWdp',
    price_usd: 0.085,
    market_cap: 85000000,
    volume_24h: 6000000,
    price_change_24h: 3.1,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['cat', 'pump.fun', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-06-20',
  },
  {
    name: 'Neiro on ETH',
    slug: 'neiro',
    ticker: 'NEIRO',
    description: '$NEIRO is a dog memecoin inspired by the same dog that inspired $DOGE, a Shiba Inu named Neiro. The Solana version gained significant traction in the multi-chain memecoin ecosystem.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: '9pSVGRHwqhbJwnzD8KkdxaHaHGCogWgrmpPtFnqTpump',
    price_usd: 0.00042,
    market_cap: 42000000,
    volume_24h: 3500000,
    price_change_24h: 1.9,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['dog', 'pump.fun', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-08-10',
  },
  {
    name: 'Moo Deng',
    slug: 'moodeng',
    ticker: 'MOODENG',
    description: '$MOODENG is a Solana memecoin inspired by the viral baby hippo from Thailand that took the internet by storm. It reached significant market caps fueled by mainstream media attention.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzc8WW',
    price_usd: 0.0028,
    market_cap: 28000000,
    volume_24h: 2200000,
    price_change_24h: -2.7,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['animal', 'pump.fun', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-09-20',
  },
  {
    name: 'Billy',
    slug: 'billy',
    ticker: 'BILLY',
    description: '$BILLY is a Solana memecoin with a distinctive cartoon character. It became one of the more charming and community-loved tokens in the Solana memecoin ecosystem.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: '3B5wuUrMEi5yATD7on46hKfej3pfmd7t1RKgrsN3pump',
    price_usd: 0.0015,
    market_cap: 15000000,
    volume_24h: 1100000,
    price_change_24h: 0.6,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-07-15',
  },
  {
    name: 'Harambe',
    slug: 'harambe',
    ticker: 'HARAMBE',
    description: '$HARAMBE pays tribute to the legendary gorilla who became an internet icon. The Solana memecoin version carries on the Harambe legacy in crypto form with a passionate community.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'Fch1oixTPri8zxBnmdCEADoJW2toyFHxqDZacQkwdvSP',
    price_usd: 0.0022,
    market_cap: 22000000,
    volume_24h: 1800000,
    price_change_24h: 4.5,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['animal', 'pump.fun', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-05-28',
  },
  {
    name: 'Loaf Cat',
    slug: 'loaf',
    ticker: 'LOAF',
    description: '$LOAF is a Solana cat memecoin themed around the loaf cat internet meme. It found a niche in the crowded cat memecoin market with its distinct loaf-shaped cat aesthetic.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'LoafcatSoLaNaMeMeCoiN1111111111111111111111',
    price_usd: 0.00008,
    market_cap: 800000,
    volume_24h: 90000,
    price_change_24h: -1.1,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['cat', 'pump.fun', 'meme'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-08-01',
  },
  {
    name: 'Maneki',
    slug: 'maneki',
    ticker: 'MANEKI',
    description: '$MANEKI is a Solana memecoin inspired by the Japanese lucky cat (Maneki-neko). It brings Japanese internet culture aesthetics to the Solana memecoin ecosystem.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: '25hAyBQfoDhfWx9ay6rarbgvWGwDdNqcHsXS3jQ3mTDJ',
    price_usd: 0.0012,
    market_cap: 12000000,
    volume_24h: 900000,
    price_change_24h: 2.4,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['cat', 'pump.fun', 'meme', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-05-15',
  },
  {
    name: 'Monke',
    slug: 'monke',
    ticker: 'MONKE',
    description: '$MONKE is a Solana memecoin celebrating monkey-brained crypto culture. It appeals to the degenerate trading community on Solana that embraces the primal instinct of chasing pumps.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'MoNkEsOLaNa1111111111111111111111111111111111',
    price_usd: 0.000045,
    market_cap: 450000,
    volume_24h: 55000,
    price_change_24h: 0.2,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['animal', 'pump.fun', 'meme'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-06-01',
  },
  {
    name: 'Samoyedcoin',
    slug: 'samo',
    ticker: 'SAMO',
    description: '$SAMO (Samoyedcoin) is one of the original Solana dog memecoins, featuring the Samoyed dog breed. It is considered a community ambassador for the Solana ecosystem.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    price_usd: 0.0045,
    market_cap: 45000000,
    volume_24h: 3200000,
    price_change_24h: 1.6,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['dog', 'community', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-05-01',
  },
  {
    name: 'ACT I: The AI Prophecy',
    slug: 'act',
    ticker: 'ACT',
    description: '$ACT is a Solana memecoin from the AI agent meta wave of late 2024. It combines narrative-driven tokenomics with AI themes, reaching significant market caps during the AI memecoin mania.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'GJAFwWjJ3vnTsrZaHFSbgNj67W3bN4t2hBagkPpumphT',
    price_usd: 0.32,
    market_cap: 320000000,
    volume_24h: 25000000,
    price_change_24h: -4.2,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['ai', 'pump.fun', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-11-01',
  },
  {
    name: 'ai16z',
    slug: 'ai16z',
    ticker: 'AI16Z',
    description: '$AI16Z is the token for the ai16z DAO, an AI-powered venture capital fund run by autonomous AI agents. It became the leading AI agent token on Solana during the AI memecoin supercycle.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC',
    price_usd: 1.42,
    market_cap: 1420000000,
    volume_24h: 95000000,
    price_change_24h: -5.1,
    is_featured: false,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['ai', 'pump.fun', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-10-25',
  },
  {
    name: 'Zerebro',
    slug: 'zerebro',
    ticker: 'ZEREBRO',
    description: '$ZEREBRO is an AI agent memecoin on Solana where an autonomous AI creates art, music, and posts on social media. It represents the cutting edge of AI-generated culture in crypto.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'DNkHMdMPTbdSUrBRbqnGE9ujHakknkFNFzAQKbPbpump',
    price_usd: 0.095,
    market_cap: 95000000,
    volume_24h: 7500000,
    price_change_24h: -2.8,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['ai', 'pump.fun', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-11-05',
  },
  {
    name: 'FRED',
    slug: 'fred',
    ticker: 'FRED',
    description: '$FRED is a community memecoin on Solana that became notable in the pump.fun ecosystem. Its simple name and relatable mascot drove organic community growth.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'FREDsOLaNaMeMeCoiN11111111111111111111111111',
    price_usd: 0.000028,
    market_cap: 280000,
    volume_24h: 35000,
    price_change_24h: 0.4,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'meme', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-08-15',
  },
  {
    name: 'Kamino Finance',
    slug: 'kmno',
    ticker: 'KMNO',
    description: '$KMNO is the governance token for Kamino Finance, a leading liquidity and yield optimization protocol on Solana. While not a pure memecoin, it trades alongside high-momentum Solana tokens.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS',
    price_usd: 0.065,
    market_cap: 65000000,
    volume_24h: 5000000,
    price_change_24h: 1.3,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-04-01',
  },
  {
    name: 'Orca',
    slug: 'orca',
    ticker: 'ORCA',
    description: '$ORCA is the token for Orca, one of Solana\'s leading decentralized exchanges. It is known for its user-friendly design and concentrated liquidity pools that power Solana DeFi.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE',
    price_usd: 3.85,
    market_cap: 385000000,
    volume_24h: 28000000,
    price_change_24h: 2.1,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-08-01',
  },
  {
    name: 'Jupiter',
    slug: 'jup',
    ticker: 'JUP',
    description: '$JUP is the token for Jupiter, the leading DEX aggregator on Solana that powers the best swap rates across all Solana liquidity. Its airdrop became one of the largest in Solana history.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN',
    price_usd: 0.92,
    market_cap: 1200000000,
    volume_24h: 85000000,
    price_change_24h: -1.8,
    is_featured: false,
    is_trending: true,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-01-31',
  },
  {
    name: 'Ninja',
    slug: 'ninja',
    ticker: 'NINJA',
    description: '$NINJA is a Solana memecoin themed around ninja culture and stealth movements. It gained attention in the pump.fun community for its thematic branding and quick price movements.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'NiNjAsOLaNa1111111111111111111111111111111111',
    price_usd: 0.000062,
    market_cap: 620000,
    volume_24h: 78000,
    price_change_24h: 3.7,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'meme', 'community'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-07-20',
  },
  {
    name: 'Raydium',
    slug: 'ray',
    ticker: 'RAY',
    description: '$RAY is the token for Raydium, Solana\'s first major automated market maker and DEX. It forms the foundational liquidity layer for the Solana DeFi and memecoin ecosystem.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R',
    price_usd: 2.85,
    market_cap: 285000000,
    volume_24h: 22000000,
    price_change_24h: 0.9,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-02-01',
  },
  {
    name: 'Render',
    slug: 'render',
    ticker: 'RENDER',
    description: '$RENDER is the token for the Render Network, a distributed GPU rendering platform. After migrating to Solana, it became one of the largest Solana ecosystem tokens by market cap.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof',
    price_usd: 5.25,
    market_cap: 2100000000,
    volume_24h: 150000000,
    price_change_24h: -2.4,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['ai', 'defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2023-11-01',
  },
  {
    name: 'Step Finance',
    slug: 'step',
    ticker: 'STEP',
    description: '$STEP is the token for Step Finance, a Solana portfolio management and yield aggregation platform. It provides a dashboard for tracking and optimizing Solana DeFi positions.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT',
    price_usd: 0.052,
    market_cap: 26000000,
    volume_24h: 1800000,
    price_change_24h: 1.2,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-04-01',
  },
  {
    name: 'CROW',
    slug: 'crow',
    ticker: 'CROW',
    description: '$CROW is a Solana memecoin featuring a crow mascot. It emerged during the pump.fun era and gained a following among bird-themed memecoin enthusiasts.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'CROwsOLaNa11111111111111111111111111111111111',
    price_usd: 0.000015,
    market_cap: 150000,
    volume_24h: 18000,
    price_change_24h: -0.8,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['pump.fun', 'animal', 'meme'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-09-01',
  },
  {
    name: 'Nyan Cat',
    slug: 'nyan',
    ticker: 'NYAN',
    description: '$NYAN brings the iconic Nyan Cat internet meme to the Solana blockchain. The rainbow-trailing pop-tart cat remains one of the most recognizable internet memes and found new life as a Solana token.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'pump.fun',
    contract_address: 'NYaNsOLaNa111111111111111111111111111111111111',
    price_usd: 0.000038,
    market_cap: 380000,
    volume_24h: 48000,
    price_change_24h: 2.1,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['cat', 'pump.fun', 'meme'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2024-06-15',
  },
  {
    name: 'Tulip Protocol',
    slug: 'tulip',
    ticker: 'TULIP',
    description: '$TULIP is the token for Tulip Protocol, one of the first yield aggregators on Solana. It helped define the early Solana DeFi ecosystem.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'TuLipcqtGVXP9XR62wM8WWCm6a9vhLs7T1uoWBk6FDs',
    price_usd: 0.025,
    market_cap: 5000000,
    volume_24h: 350000,
    price_change_24h: -0.3,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-06-01',
  },
  {
    name: 'Solanium',
    slug: 'slim',
    ticker: 'SLIM',
    description: '$SLIM is the token for Solanium, a decentralized fundraising and liquidity platform on Solana. It was one of the first launchpads for Solana projects.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'xxxxa1sKNGwFtw2kFn8XauW9xq8hBZ5kVtcSesTT9fW',
    price_usd: 0.018,
    market_cap: 3600000,
    volume_24h: 280000,
    price_change_24h: 0.5,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-05-15',
  },
  {
    name: 'Sunny Aggregator',
    slug: 'sunny',
    ticker: 'SUNNY',
    description: '$SUNNY is the token for Sunny Aggregator, a Solana yield farming optimizer. It aggregated yields across Solana DeFi protocols for maximum returns.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'SUNNYWgPQmFxe9wTZzNK7iPnJ3vYDrkgnxJRJm1s3ag',
    price_usd: 0.000085,
    market_cap: 170000,
    volume_24h: 12000,
    price_change_24h: -1.4,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-08-15',
  },
  {
    name: 'Cope',
    slug: 'cope',
    ticker: 'COPE',
    description: '$COPE was an early Solana meme/utility token built around a trading leaderboard concept. It became a cultural artifact of early Solana DeFi and community speculation.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: '8HGyAAB1yoM1ttS7pXjHMa3dukTFGQggnFFH3hJZgzQh',
    price_usd: 0.0022,
    market_cap: 440000,
    volume_24h: 55000,
    price_change_24h: 0.1,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['meme', 'community', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-03-01',
  },
  {
    name: 'Oxygen',
    slug: 'oxy',
    ticker: 'OXY',
    description: '$OXY is the token for Oxygen Protocol, a DeFi prime brokerage built on Solana. It enables users to borrow, lend, and trade against their portfolio.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'z3dn17yLaGMKffVogeFHQ9zWVcXgqgf3PQnDsNs2g6M',
    price_usd: 0.0012,
    market_cap: 2400000,
    volume_24h: 180000,
    price_change_24h: 0.7,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2021-07-01',
  },
  {
    name: 'Bonfida',
    slug: 'fida',
    ticker: 'FIDA',
    description: '$FIDA is the token for Bonfida, a suite of Solana products including Serum DEX trading tools, Solana Name Service (.sol domains), and trading bots.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'EchesyfXePKdLtoiZSL8pBe8Myagyy8ZRqsACNCFGnvp',
    price_usd: 0.28,
    market_cap: 28000000,
    volume_24h: 2200000,
    price_change_24h: -0.6,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2020-12-01',
  },
  {
    name: 'Pyth Network',
    slug: 'pyth',
    ticker: 'PYTH',
    description: '$PYTH is the token for Pyth Network, the leading oracle solution on Solana providing real-time price data for DeFi applications. It is one of the most critical infrastructure tokens in the Solana ecosystem.',
    long_description: '',
    chain: 'solana',
    launch_platform: 'raydium',
    contract_address: 'HZ1JovNiVvGqswpAD2uZK2po6537k7mQsyLRxQFbtyDV',
    price_usd: 0.38,
    market_cap: 760000000,
    volume_24h: 55000000,
    price_change_24h: 1.5,
    is_featured: false,
    is_trending: false,
    is_new: false,
    is_indexed: true,
    tags: ['defi', 'solana-ecosystem'],
    logo_url: '',
    banner_url: '',
    data_source: 'manual',
    external_data_id: '',
    launch_date: '2023-11-20',
  },
];
